version: '3'
services:
  laravel-nginx:
    container_name: "laravel-nginx"
    build:
      context: ./docker/nginx
    depends_on:
      - laravel-app
    ports:
      - 80:80
    volumes:
      - ./:/src

  laravel-app:
    container_name: "laravel-app"
    build:
      context: ./docker/php
    depends_on:
      - laravel-mysql
    ports:
      - 5173:5173
    volumes:
      - ./:/src
      - /src/node_modules
      - /src/vendor
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  laravel-mysql:
    image: mysql:8.0.28
    container_name: laravel-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kuri-db
      TZ: "Asia/Tokyo"
    volumes:
      - .my.cnf:/etc/mysql/conf.d/my.cnf

  laravel-redis:
    image: redis:alpine
    container_name: "laravel-redis"
    ports:
      - 16379:6379