version: '3'
services:
  nginx:
    container_name: "nginx"
    build:
      context: ./docker/nginx
    depends_on:
      - php
    ports:
      - 80:80
    networks:
      - waku-waku-network
    volumes:
      - ./:/src

  php:
    container_name: "php"
    build:
      context: ./docker/php
    ports:
      - 5173:5173
    networks:
      - waku-waku-network
    volumes:
      - ./:/src
      - /src/node_modules
      - /src/vendor
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

networks:
  waku-waku-network:
    driver: bridge