version: '3.9'
services:
  nginx:
    container_name: "nginx"
    build:
      context: ./docker/nginx
    depends_on:
      - php
    ports:
      - 80:80
    networks:
      - waku-waku-network
    volumes:
      - ./:/src

  php:
    container_name: "php"
    build:
      context: ./docker/php
    ports:
      - 5173:5173
    networks:
      - waku-waku-network
    volumes:
      - ./:/src
      - /src/node_modules
      - /src/vendor
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
  
  mysql:
    image: mysql:8.0.28
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - waku-waku-network
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

networks:
  waku-waku-network:
    driver: bridge